### PR TITLE
#169257391 setup api docs using swagger

### PR DESCRIPTION
**Pull request by nshaphan**
#### What does this PR do?
Setup API documentation using swagger

#### Description of Task to be completed
- [x] creating API specs file, swagger.json
- [x] swagger UI integration

#### How should this be manually tested?
- Clone the repo and do `npm install` to install dependencies
- Run `npm run test-docs`
- visit `localhost:3000/api/docs` in browser

#### Any background context you want to provide?
- Port may change depending on your environment
- `npm run test-docs` is for the testing purpose it will be removed in the future

#### What are the relevant pivotal tracker stories?
[#169257391](https://www.pivotaltracker.com/story/show/169257391)

#### Screenshots (if appropriate)
image

### CODE REVIEW

**Review by timolinn — COMMENTED** [review]
Great work so far @nshaphan!

How was `swagger.json` generated?

**Comment by nshaphan** [comment]
> Great work so far @nshaphan!
> 
> How was `swagger.json` generated?

- To generate swagger.json, visit https://editor.swagger.io/
- They provide a sample API doc using YAML
- Download the sample as JSON using **File menu > save as JSON**
- Then open a downloaded file, copy its content and paste it back to https://editor.swagger.io/ editor
- Then edit the file to your liking, using the docs https://swagger.io/docs/specification/2-0/
- Finally, download the final file again

**Comment by timolinn** [comment]
@nshaphan This is a long process. We need to be able to automatically generate documentation with every new endpoint. If it doesn't happen already, kindly checkout this package https://github.com/mpashkovskiy/express-oas-generator

**Comment by nshaphan** [comment]
> https://github.com/mpashkovskiy/express-oas-generator

**Comment by nshaphan** [comment]
> @nshaphan This is a long process. We need to be able to automatically generate documentation with every new endpoint. If it doesn't happen already, kindly checkout this package https://github.com/mpashkovskiy/express-oas-generator

Thanks for feedback @timolinn, I have been using the wrong method, in the pivotal tracker story, I found that they proposed using JSDoc for API Documentation.

**Pull request closed without merging**
