### PR TITLE
#170176680 adds foreign keys for validations

### PR DESCRIPTION
**Pull request by b0nbon1**
#### What does this PR do?
Fixes the database by adding foreign keys to it and also fixing failing tests. Changing some columns like locations to use foreign keys.
#### Description of Task to be completed?
- [x] add seeds for cities
- [x] fixed failing tests
- [x] changing locations on trips to use foreign keys so as to use existing locations in the DB instead of typing the cities.
- [x] added foreign key constraint to `lineManagerId` column on table `users`  to point `users` table so as to provide the `sequelizeConstraintValidition` when violated. 
- [x] added foreign key constraint to `userId` column on table `hotels` to point `users` table so as to throw error `sequelizeConstraintValidition` when violated. 
- [x] added foreign key constraint to `locationId` column on table `hotels` to point `locations` table so as to throw error  `sequelizeConstraintValidition` when violated. 
- [x] added foreign key constraint to `hotelId` column on table `trips` to point `hotels` table so as to throw error  `sequelizeConstraintValidition` when violated. 
- [x] added foreign key constraint to `UserId` column on table `trips` to point `users` table so as to throw error  `sequelizeConstraintValidition` when violated. 
- [x] added foreign key constraint to `requestId` column on table `trips` to point `requests` table so as to throw error  `sequelizeConstraintValidition` when violated. 
- [x] added foreign key constraint to `userId` column on table `bookings` to point `users` table so as to throw error  `sequelizeConstraintValidition` when violated. 
- [x] added foreign key constraint to `hotelId` column on `bookings` to point `hotels` table so as to throw error  `sequelizeConstraintValidition` when violated.
- [x] added foreign key constraint to `roomId` column on table `bookings` to point `rooms` table so as to throw error  `sequelizeConstraintValidition` when violated.
- [x] added foreign key constraint to `tripId` column on table `bookings` table to point `trips` table so as to throw error  `sequelizeConstraintValidition` when violated. 
- [x] added foreign key constraint to `userId` column on `requests` table to point `users` table so as to throw error  `sequelizeConstraintValidition` when violated. 
- [x] added foreign key constraint to `userId` column on `comments` table to point `users` table so as to throw error  `sequelizeConstraintValidition` when violated. 
- [x] added foreign key constraint to `requestId` column on `comments` table to point `requests` table so as to throw error  `sequelizeConstraintValidition` when violated.
- [x] added foreign key constraint to `userId` column on `conversations` table to point `users` table so as to throw error `sequelizeConstraintValidition` when violated.
- [x] added foreign key constraint to `userId` column on `ratings` table to point `users` table so as to throw error  `sequelizeConstraintValidition` when violated.
#### How should this be manually tested?
- git clone the repo and switch branch to `bg-fixing-foreign-keys-database-170176680`
- run `npm install` to install the dependencies.
- run `npm run migrate` to migrate
- run `npm run db:seed` to seed users and location to database
- signin
- create hotels
- then create trips.
*run tests*
- run `npm run pretest-travis` to run migrations to test database.
- run `npm test` to run the tests.
#### Any background context you want to provide?
- many tests were failing because of `sequelizeContsraintsValidation`
#### What are the relevant pivotal tracker stories?
[#170176680](https://www.pivotaltracker.com/n/projects/2407417/stories/170176680)
#### Screenshots:
*one way trip*

image

*return trip*

image

*multi city trip*

image

### CODE REVIEW

**Review by nshaphan — APPROVED** [review]
Great work, @b0nbon1 , but I think that we would need another endpoint to add/remove locations.

**Review by gildniy — APPROVED** [review]
Tested and working correctly.

**Comment by b0nbon1** [comment]
> Great work, @b0nbon1 , but I think that we would need another endpoint to add/remove locations.

I think that would be done on another story, this one was just fixing the foreign keys

**Review by Mastel22 — APPROVED** [review]
Great job @b0nbon1 . Tested and it's working as intended.

**Comment by kipropbrian** [comment]
What about trip types?

**Comment by kipropbrian** [comment]
Can you also describe in detail what foreign keys you changed and why

**Comment by b0nbon1** [comment]
> Can you also describe in detail what foreign keys you changed and why

Thanks, I have included it on the description

**Comment by b0nbon1** [comment]
> What about trip types?

could you please clarify?

**Comment by kipropbrian** [comment]
Looks good.

**Review by Billmike — APPROVED** [review]

**Pull request merged**
