### PR TITLE
#169861079 Fix Hound CI Error on Pull Request

### PR DESCRIPTION
**Pull request by gildniy**
#### What does this PR do?
Fixes the errors where Hound CI was complaining about the commit for PRs
#### Description of Task to be completed?
- [x] Set the Hound dashboard from using the organization hound configuration file and use the project one
- [x] Created the project hound configuration file on the root (.hound.yml)
#### How should this be manually tested?
- Push the commit and then raise a PR from it, if your code was approved by Husky on local, it will be approved also by Hound
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#169861079](https://www.pivotaltracker.com/story/show/169861079)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Review by timolinn — DISMISSED** [review]

**Review by RaymondMwaura — DISMISSED** [review]
This is a good initiative. Kepp up the good work.

**Review by b0nbon1 — DISMISSED** [review]
Nice one. I think its ready to be merged

**Review by RaymondMwaura — COMMENTED** [review]
Are there any more changes to the file? I see you have pushed some more commits to it since I approved it. I think it's okay as it is for merge. We need it merged as soon as possible.

**Review by timolinn — DISMISSED** [review]

**Review by b0nbon1 — DISMISSED** [review]
I think its ready to be merged

**Review by timolinn — COMMENTED** [review]
I can't seem to find `.hound.yml` on this branch?

**Review by RaymondMwaura — DISMISSED** [review]
Keep up the pace.

**Comment by timolinn** [comment]
> I can't seem to find `.hound.yml` on this branch?

@gildniy

**Review by RaymondMwaura — APPROVED** [review]
@timolinn That was a good spot on the missing '.hound.yml' file. Good job Gildas.

**Review by b0nbon1 — APPROVED** [review]

**Review by timolinn — APPROVED** [review]

**Pull request merged**
