### PR TITLE
#170455359 fixes redirection from email to update page

### PR DESCRIPTION
**Pull request by b0nbon1**
#### What does this PR do?
Fixes the missing redirection links from email to frontend
#### Description of Task to be completed?
- make the links to be gotten from the query
- add front-end links for cors
#### How should this be manually tested?
- git clone the repo
- run `npm install` to install dependencies
- run `npm run migrate` to make migrations
- run `npm run db:seed` to seed the database
- run `npm run pretest-travis` and then `npm test` to run the tests 
- got to forgot password route and run `{{url}}/api/v1/auth/forgotPassword?host={host}` replace with your frontend link
- check your email to confirm redirection.
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
[#170455359](https://www.pivotaltracker.com/n/projects/2407417/stories/170455359)
#### Screenshots:
email:
image
redirect:
image

### CODE REVIEW

**Review by Billmike — DISMISSED** [review]

**Review by Mastel22 — APPROVED** [review]
LGTM

**Review by nshaphan — APPROVED** [review]
LGTM

**Review by gildniy — APPROVED** [review]
Tested and working

**Review by RaymondMwaura — APPROVED** [review]
Great work. We really needed the CORS fix as well which I see you have included. Let's get this merged as soon as possible.

**Pull request merged**
