### PR TITLE
#169257424 Users can edit trips with request status "Open"

### PR DESCRIPTION
**Pull request by RaymondMwaura**
#### What does this PR do?
This PR allows users to update their trip request details

#### Description of Task to be completed?
- [x] Create a trip update endpoint
- [x] Update trip controller to allow updating of trips

#### How should this be manually tested?
- Clone this branch then navigate to the project folder using Terminal
- Install dependencies using `npm install`
- Prepare the dev environment by running the command `npm run migrate:undo` then `npm run migrate`
- Using Postman:
   - Sign up a user
   - Create a trip and capture its request id
   - Use the endpoint for getting one request (by id) to fetch the id of the trip you have just created that is nested within the request
   - Update the trip using the fetched id above by making a 'PATCH' request on the endpoint 'http://localhost:3000/api/v1/trips/:tripId'
```
JSON - RAW
{
    "leavingFrom": "Kampala",
    "goingTo": "Nairobi",
    "travelDate": "2019-11-18",
    "returnDate": "2019-11-18",
    "reason": "visit our new country office",
    "hotelId": 1,
    "type": "return",
    "rooms": [2,4]
  }
```

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#169257424](https://www.pivotaltracker.com/story/show/169257424)

#### Screenshots (if appropriate)
Screen Shot 2019-11-28 at 07 56 50

#### Questions:
N/A

### CODE REVIEW

**Comment by timolinn** [comment]
@RaymondMwaura Please fix conflicts.

**Review by timolinn — DISMISSED** [review]
Looks great!

**Review by b0nbon1 — DISMISSED** [review]
Great job @RaymondMwaura especially the way you have handled the updated trip. I think its ready to be merged

**Comment by nshaphan** [comment]
Great Works,  trips can be updated successfully. However booked rooms are not updated, I think that you can work on that one too!

**Comment by RaymondMwaura** [comment]
> Great Works, trips can be updated successfully. However booked rooms are not updated, I think that you can work on that one too!

I have implemeted this, you can test it out now and see if it works.

**Review by b0nbon1 — APPROVED** [review]
Nice work @RaymondMwaura . I have tested and it is working.

**Review by timolinn — APPROVED** [review]

**Review by nshaphan — APPROVED** [review]
Well done, @RaymondMwaura

**Pull request merged**
