### PR TITLE
Retrieve feedback on accomodation

### PR DESCRIPTION
**Pull request by nshaphan**
#### What does this PR do?
Retrieve feedback on accommodation

#### Description of Task to be completed?
- [x] retrieve feedback on accommodation for travel admin, requester, supplier

#### How should this be manually tested?
- clone this repo and open the project 
- install all dependencies using `npm install`
- checkout to `bg-fix-retrieve-feedback-170944759` branch
- in postman login as a requester `book accommodation`, and provide feedback on that accommodation using `POST hotels/:hotelId/feedback`
- Log in as the `travel admin` to retrieve feedback on the hotel using `GET hotels/:hotelId/feedback`.
#### Any background context you want to provide?
This fix is needed for travel admins, requesters, suppliers to view all feedback provided. 

#### What are the relevant pivotal tracker stories?
[#170944759](https://www.pivotaltracker.com/story/show/170944759)

#### Screenshots (if appropriate)
image

#### Questions:
N/A

### CODE REVIEW

**Review by gildniy — DISMISSED** [review]
Tested and working.

**Review by b0nbon1 — DISMISSED** [review]

**Review by gildniy — DISMISSED** [review]

**Review by RaymondMwaura — DISMISSED** [review]
LGTM

**Review by Mastel22 — DISMISSED** [review]
LGTM

**Review by gildniy — DISMISSED** [review]

**Review by b0nbon1 — DISMISSED** [review]
LGTM

**Review by RaymondMwaura — DISMISSED** [review]
LGTM

**Review by Mastel22 — DISMISSED** [review]

**Review by b0nbon1 — APPROVED** [review]

**Review by Mastel22 — APPROVED** [review]

**Review by Billmike — APPROVED** [review]

**Pull request merged**
