### PR TITLE
#169257433 Users should be able to chat on the public chat

### PR DESCRIPTION
**Pull request by b0nbon1**
#### What does this PR do?
 Enables users to post messages on the public chat and also view sent messages from other users
#### Description of Task to be completed?

- [x] add socket.io
- [x] create a messages event listener
- [x] save messages
- [x] broadcast messages to all users

#### How should this be manually tested?

- run `npm install` to install dependencies
- run `npm run migrate` to create table notifications
- run `npm run watch` to run the server
- signup to two users
- go to `./public/templates/pages/chatTest.html ` run it on your browser
- then at the end of the URL, add query `?token=` followed by the token of the first user. do the same to the second user on another tab of the browser
- then type and send a message.
- run npm `pretest-travis` followed by `npm test`
#### Any background context you want to provide?
- This feature uses WebSockets that is `socket.io`
#### What are the relevant pivotal tracker stories?
[#169257433](https://www.pivotaltracker.com/n/projects/2407417/stories/169257433)
#### Screenshots:

image
image

### CODE REVIEW

**Review by gildniy — APPROVED** [review]
Tested and working. I think it can be merged.

**Comment by nshaphan** [comment]
I am unable to test this feature manually,  this file doesn't exist `./public/templates/views/index.html` maybe you can update the description for this pull request

**Comment by b0nbon1** [comment]
> I am unable to test this feature manually, this file doesn't exist `./public/templates/views/index.html` maybe you can update the description for this pull request

Thanks @nshaphan I have updated the PR description now check

**Review by nshaphan — APPROVED** [review]
Awesome, @b0nbon1, great works. liked the how broke down the feature into small reusable and understandable functions

**Review by collinewait — APPROVED** [review]

**Pull request merged**
