### PR TITLE
#169257431 Statistics of trips made in the last X timeframe

### PR DESCRIPTION
**Pull request by gildniy**
#### What does this PR do?
It lists and counts the trips made in the last X timeframe by an individual user
#### Description of Task to be completed?
- Add tests for testing the functionality
- Add the endpoint `POST /api/v1/trips/stats` for retrieving the statistics of the trip
- Add a controller and service to handle the retrieval
#### How should this be manually tested?
- Clone the repo on the local machine
- Run `npm install` to install the dependencies
- As a logged in user of role `requester`, I can post a date in the `fromDate` field,  and a list and count of all trips I made from that provided date up to now will be retrieved
- As a logged user of role `manager`, I can post a date in the `fromDate` field, and an id of one of users I manage in the `userId` field, and a list and count of all trips made by the user whose id provided  and from that provided date up to now will be retrieved
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#169257431](https://www.pivotaltracker.com/story/show/169257431)
#### Screenshots (if appropriate)
N/A
image
image

#### Questions:
N/A

### CODE REVIEW

**Review by b0nbon1 — CHANGES_REQUESTED** [review]
Hey @gildniy, I have reviewed and I have confirmed that the feature is working perfectly.
though I think you missed an edge-case on your validation and that is if I don't pass any data on the body it provides this:
image
which is not a good message to pass to the user maybe do some modification on the response

**Comment by gildniy** [comment]
> Hey @gildniy, I have reviewed and I have confirmed that the feature is working perfectly.
> though I think you missed an edge-case on your validation and that is if I don't pass any data on the body it provides this:
> image
> which is not a good message to pass to the user maybe do some modification on the response

Thanks @b0nbon1 , now resolved you can test it again.

**Review by b0nbon1 — DISMISSED** [review]
Great work @gildniy, I like the way you fetched the trips that have been traveled for a certain period especially the line. I have reviewed and it is working accordingly.

**Review by Mastel22 — DISMISSED** [review]
Looks great.Nice job

**Review by b0nbon1 — APPROVED** [review]

**Review by Mastel22 — APPROVED** [review]

**Review by nshaphan — APPROVED** [review]
Great works, @gildniy this feature is well implemented and working properly

**Review by collinewait — APPROVED** [review]

**Pull request merged**
