### PR TITLE
#171326822 Add profile picture to user profile

### PR DESCRIPTION
**Pull request by RaymondMwaura**
#### What does this PR do?
Allows a user to add and update a profile picture to their profile

#### Description of Task to be completed?
- [x] add a profile picture field to the users' table
- [x] update models, controllers, and services
- [x] refactor tests

#### How should this be manually tested?
- clone this repo and install dependencies
- run tests using `npm run pretest-travis  && npm test`
- test with Postman
  - start the server with `npm run watch`
  - make a request to the endpoint '{{url}}/api/v1/user/update-profile' and include a profile picture using a form request as follows:
Screen Shot 2020-02-20 at 12 38 18

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#171326822](https://www.pivotaltracker.com/story/show/171326822)

#### Screenshots (if appropriate)
Screen Shot 2020-02-20 at 12 42 46

#### Questions:
N/A

### CODE REVIEW

**Review by nshaphan — DISMISSED** [review]
Great job @RaymondMwaura , working properly

**Review by b0nbon1 — DISMISSED** [review]
I used it to test front-end and I think it's working perfectly

**Review by nshaphan — APPROVED** [review]

**Review by b0nbon1 — APPROVED** [review]
Great job @RaymondMwaura

**Review by Mastel22 — APPROVED** [review]
LGTM

**Review by gildniy — APPROVED** [review]
Tested and working, good job @RaymondMwaura

**Pull request merged**
