### PR TITLE
#169257429 Feedback on accommodation facilities

### PR DESCRIPTION
**Pull request by gildniy**
#### What does this PR do?
Adds a feature to allow the users to provide feedback on an accommodation facility.
#### Description of Task to be completed?
- [x] Add a feedback database table and model files with as fields `userId`, `hotelId` and `feedback`
- [x] Add an endpoint `POST /api/v1/hotels/:hotelId/feedback`
- [x] Add controller and service function to handle the feedback post
#### How should this be manually tested?
- Clone the project on local machine
- Run `npm run migration` to run the database migrations
- Run `npm run watch` to start the server
- In postman, you need to be signed in. Create a hotel and go to the endpoint `POST /api/v1/hotels/:hotelId/feedback` and in the body add the feeback object:
```
{
  " feeback": "This is an example feeback!"
}
```
and hit on `Send` button. A response containing the created feedback object will appear
#### Any background context you want to provide?
- For this feature to be working, a verified user need to be logged in, and the hotel whose `id` was provided in the URL may be present.
#### What are the relevant pivotal tracker stories?
[#169257429](https://www.pivotaltracker.com/story/show/169257429)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Review by b0nbon1 — CHANGES_REQUESTED** [review]
Hey @nshaphan , please resolve the conflicts.

**Comment by collinewait** [comment]
Resolve conflicts @gildniy

**Comment by gildniy** [comment]
> Resolve conflicts @gildniy

Resolved, thanks!

**Review by b0nbon1 — APPROVED** [review]
I have tested it and I think now it's ready to be merged

**Review by Mastel22 — APPROVED** [review]

**Review by collinewait — APPROVED** [review]

**Pull request merged**
